# Generated by Django 4.2.2 on 2023-07-01 09:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('vo', 'Voice Over'), ('bg_music', 'Background Music'), ('video_music', 'Video Music')], max_length=20)),
                ('high_volume', models.FloatField()),
                ('low_volume', models.FloatField()),
                ('video_component_id', models.UUIDField(null=True)),
                ('url', models.URLField(null=True)),
                ('duration_start_time', models.FloatField(null=True)),
                ('duration_end_time', models.FloatField(null=True)),
            ],
        ),
    ]
