# Generated by Django 4.2.2 on 2023-07-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio_Elements', '0002_alter_audioelement_video_component_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioelement',
            name='video_component_id',
            field=models.UUIDField(null=True),
        ),
    ]
