# Generated by Django 4.2.2 on 2023-07-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio_Elements', '0003_alter_audioelement_video_component_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioelement',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
